'use client'
import { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Menu, Search, X, LogOut, Plus } from 'lucide-react'
import { SITE_CONFIG } from '@/lib/site-config'
import { useEditableLocalAuthSession } from '@/editable/components/EditableLocalAuthForms'

const links=[['Home','/'],['Listings','/listing'],['About','/about'],['Search','/search']] as const
export function EditableNavbar(){const [open,setOpen]=useState(false);const pathname=usePathname();const {session,logout}=useEditableLocalAuthSession();return <header className="sticky top-0 z-50 bg-[#111b2b]/95 text-white backdrop-blur-xl"><div className="h-1 bg-[linear-gradient(90deg,#4267e9,#ffb300,#4267e9)]"/><nav className="mx-auto flex min-h-[78px] max-w-[1180px] items-center gap-6 px-5 sm:px-8"><Link href="/" className="mr-auto flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white"><img src="/favicon.png?v=20260413" alt="" className="h-8 w-8 object-contain"/></span><span><b className="block text-xl leading-none">{SITE_CONFIG.name}</b><small className="mt-1 block text-[9px] font-bold uppercase tracking-[.22em] text-slate-400">Read · discover · connect</small></span></Link><div className="hidden items-center gap-7 lg:flex">{links.map(([label,href])=><Link key={href} href={href} className={`text-sm font-bold transition hover:text-[#ffb300] ${pathname===href?'text-[#ffb300]':'text-slate-200'}`}>{label}</Link>)}</div><form action="/search" className="hidden items-center rounded-full border border-white/15 bg-white/5 px-3 xl:flex"><Search className="h-4 w-4 text-slate-400"/><input name="q" aria-label="Search" className="w-24 bg-transparent px-2 py-2 text-sm outline-none placeholder:text-slate-500" placeholder="Search"/></form><div className="hidden items-center gap-2 sm:flex">{session?<><span className="max-w-28 truncate px-2 text-sm font-bold text-[#ffb300]">{session.name}</span><Link href="/create" className="inline-flex items-center gap-1.5 rounded-lg bg-[#4267e9] px-3 py-2 text-sm font-bold"><Plus className="h-4 w-4"/>Create</Link><button onClick={logout} className="inline-flex items-center gap-1.5 px-2 py-2 text-sm font-bold text-slate-300"><LogOut className="h-4 w-4"/>Logout</button></>:<><Link href="/login" className="px-3 py-2 text-sm font-bold">Login</Link><Link href="/signup" className="rounded-lg bg-[#ffb300] px-4 py-2 text-sm font-extrabold text-[#111b2b]">Sign up</Link></>}</div><button aria-label="Toggle menu" onClick={()=>setOpen(!open)} className="rounded-lg border border-white/15 p-2 lg:hidden">{open?<X/>:<Menu/>}</button></nav>{open?<div className="border-t border-white/10 px-5 py-5 lg:hidden"><div className="grid gap-1">{links.map(([label,href])=><Link onClick={()=>setOpen(false)} key={href} href={href} className="rounded-lg px-4 py-3 font-bold hover:bg-white/5">{label}</Link>)}{session?<><Link href="/create" className="rounded-lg px-4 py-3 font-bold">Create</Link><button onClick={logout} className="px-4 py-3 text-left font-bold">Logout</button></>:<><Link href="/login" className="rounded-lg px-4 py-3 font-bold">Login</Link><Link href="/signup" className="rounded-lg px-4 py-3 font-bold text-[#ffb300]">Sign up</Link></>}</div></div>:null}</header>}
